version: "3.9"

services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - websockets
      - scheduler
      - worker
      - mariadb
      - minio
      - redis
      - meilisearch

  nginx:
    image: wodby/nginx:1.19-5.15.0
    networks:
      default:
        aliases:
          - api
    ports:
      - '${FORWARD_NGINX_PORT:-80}:80'
    environment:
      NGINX_VHOST_PRESET: 'php'
      NGINX_BACKEND_HOST: 'app'
      NGINX_SERVER_ROOT: '/var/www/html/public'
      NGINX_STATIC_EXT_REGEX: 'cur|jpe?g|gif|htc|ico|png|xml|otf|ttf|eot|woff|woff2|svg|mp4|svgz|ogg|ogv|pdf|pptx?|zip|tgz|gz|rar|bz2|doc|xls|exe|tar|mid|midi|wav|bmp|rtf|txt|map|webp|json|html'
    volumes:
      - app:/var/www/html
    depends_on:
      - app

  websockets:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    ports:
      - '${FORWARD_WEBSOCKETS_PORT:-6001}:6001'
    volumes:
      - app:/var/www/html:ro
    command: php artisan websockets:serve

  scheduler:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    volumes:
      - app:/var/www/html:ro
    command: watch -tn 60 php artisan schedule:run
    depends_on:
      - redis

  worker:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    volumes:
      - app:/var/www/html:ro
    command: php artisan queue:work --verbose --tries=3 --timeout=60
    depends_on:
      - redis

  mariadb:
    image: mariadb:10
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s

  minio:
    image: minio/minio:latest
    ports:
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: '${S3_ACCESS_KEY_ID}'
      MINIO_ROOT_PASSWORD: '${S3_SECRET_ACCESS_KEY}'
    volumes:
      - minio:/data/minio
    entrypoint: sh
    command: -c mkdir -p /data/minio/local && minio server /data/minio --console-address ":8900"
    healthcheck:
      test: [CMD, curl, -f, http://localhost:9000/minio/health/live]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    healthcheck:
      test: [CMD, redis-cli, ping]
      retries: 3
      timeout: 5s

  meilisearch:
    image: getmeili/meilisearch:v0.30.4
    environment:
      MEILI_ENV: '${MEILI_ENV:-production}'
      MEILI_NO_ANALYTICS: true
    volumes:
      - meilisearch:/data.ms
    healthcheck:
      test: [CMD, wget, --no-verbose, --spider,  http://localhost:7700/health]
      retries: 3
      timeout: 5s

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

networks:
  default:
    name: docker-template

volumes:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}
  mariadb:
    driver: local
  minio:
    driver: local
  redis:
    driver: local
  meilisearch:
    driver: local
